FROM python:3.10-alpine AS builder

WORKDIR /app

COPY sample_client/app.py /app
COPY sample_client/templates/index.html /app
COPY sample_client/templates/success.html /app
COPY sample_client/templates/error.html /app
COPY sample_client/requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["app.py"]
